[package]
name = "stain"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
stain-macros = { workspace = true }
parking_lot = { version = "0.12.4", features = ["send_guard"] }
inventory = "0.3.15"
itertools = "0.14.0"
